# Generated by Django 5.0.3 on 2024-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_receipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_ingredients',
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_ingredients',
            field=models.ManyToManyField(to='vege.ingredient'),
        ),
    ]
