# Generated by Django 5.0.3 on 2024-07-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_ingredient_remove_receipe_receipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
